#workflow to create a pip 

name: PIP Module - Prod
on:
    workflow_dispatch:
        inputs:
            tf_action:
                description: "Terraform action to perform (plan, apply, destroy)"
                default: "plan"
                required: true
    workflow_call:
        inputs:
            tf_action:
                description: "Terraform action to perform (plan, apply, destroy)"
                required: true
                type: string
jobs:
    pip:
        uses: ./.github/workflows/reusableworkflow.yaml
        with:
            tf_action: ${{ inputs.tf_action }}
            module: "pip"
            tfvars: "../../environments/prod/tfvars/pip.tfvars"
            backend: "../../environments/prod/backend/pip.backend.hcl"
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        permissions:
            contents: read
            id-token: write