# workflow for vnet module
name: Vnet Module - Prod

on:
    workflow_dispatch:
        inputs:
            tf_action:
                description: "terraform action to perform (plan, apply, destroy)"
                required: true
                default: "plan"
    workflow_call:
        inputs:
            tf_action:
                description: "terraform action to perform (plan, apply, destroy)"
                required: true
                default: "plan"
                type: string
jobs:
    vnet:
        uses: ./.github/workflows/reusableworkflow.yaml
        with:
            module: "vnet"
            tfvars: "../../environments/prod/tfvars/vnet.tfvars"
            backend: "../../environments/prod/backend/vnet.backend.hcl"
            tf_action: ${{ inputs.tf_action }}
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        permissions:
            id-token: write
            contents: read
